// Canonical list of agent platform pages and integration pages for SEO discovery

export const AGENT_PAGES: { slug: string; name: string; desc: string }[] = [
  { slug: "cursor",             name: "Cursor",                desc: "AI code editor. Access 15,253+ niimo skills directly from your Cursor workspace." },
  { slug: "windsurf",           name: "Windsurf",              desc: "Windsurf AI IDE. Run certified niimo skills inside Windsurf flows without local setup." },
  { slug: "kiro",               name: "Kiro",                  desc: "Kiro agent platform. Execute niimo skills via a single API key from Kiro." },
  { slug: "vscode",             name: "VS Code + Continue",    desc: "VS Code with Continue. Extend your AI coding assistant with 15,253+ server-side skills." },
  { slug: "jetbrains",          name: "JetBrains AI",          desc: "JetBrains AI. Integrate certified niimo skills into your JetBrains IDE workflow." },
  { slug: "kilocode",           name: "Kilo Code",             desc: "Kilo Code agent. Use niimo's skill library to supercharge Kilo Code automations." },
  { slug: "zencoder",           name: "Zencoder",              desc: "Zencoder AI. Call niimo skills from Zencoder pipelines for secure server-side execution." },
  { slug: "apple-intelligence", name: "Apple Intelligence",    desc: "Apple Intelligence integration. Connect Apple on-device AI to niimo's cloud skill library." },
  { slug: "claude-code",        name: "Claude Code",           desc: "Claude Code agent. Install the niimo skill pack to give Claude access to 15,253+ certified skills." },
  { slug: "gemini-cli",         name: "Gemini CLI",            desc: "Gemini CLI. Run niimo skills from Gemini command-line agent workflows." },
  { slug: "codex",              name: "Codex",                 desc: "OpenAI Codex. Pair Codex with niimo's certified skill library for production-safe automations." },
  { slug: "opencode",           name: "Opencode",              desc: "Opencode AI. Execute niimo skills directly inside Opencode agent sessions." },
  { slug: "nanoclaw",           name: "NanoClaw",              desc: "NanoClaw container-isolated Claude Code runner. Install /add-niimo to access 15,253+ certified skills." },
  { slug: "openclaw",           name: "OpenClaw",              desc: "OpenClaw open-source agent platform. niimo certified skills are available natively on ClaWHub." },
  { slug: "github-copilot",     name: "GitHub Copilot",        desc: "GitHub Copilot. Extend Copilot with niimo's secure, server-side AI skill library." },
  { slug: "coderabbit",         name: "Coderabbit",            desc: "Coderabbit AI code review. Pair with niimo skills for automated security and quality checks." },
  { slug: "devin",              name: "Devin",                 desc: "Devin autonomous engineer. Give Devin access to niimo's certified skill library via API." },
  { slug: "openrouter",         name: "OpenRouter",            desc: "OpenRouter model gateway. Route niimo skill calls through any LLM via OpenRouter." },
  { slug: "grok",               name: "Grok",                  desc: "xAI Grok. Connect Grok agents to niimo's 15,253+ server-side certified skills." },
  { slug: "mistral",            name: "Mistral",               desc: "Mistral AI agent. Execute niimo skills from Mistral-powered workflows." },
  { slug: "perplexity",         name: "Perplexity",            desc: "Perplexity AI. Augment Perplexity answers with real-time niimo skill execution." },
  { slug: "cohere",             name: "Cohere",                desc: "Cohere AI. Integrate niimo certified skills into Cohere agent pipelines." },
  { slug: "fireworks-ai",       name: "Fireworks AI",          desc: "Fireworks AI inference platform. Combine fast inference with niimo's skill library." },
  { slug: "replit-ai",          name: "Replit AI",             desc: "Replit AI agents. Run niimo server-side skills from Replit automation workflows." },
  { slug: "manus",              name: "Manus",                 desc: "Manus AI agent. Execute niimo's certified skill library from Manus automations." },
  { slug: "notion-ai",          name: "Notion AI",             desc: "Notion AI. Extend Notion workflows with niimo server-side skill execution." },
  { slug: "zai",                name: "Zai",                   desc: "Zai AI agent platform. Connect Zai to niimo's 15,253+ certified skills." },
  { slug: "jasper",             name: "Jasper",                desc: "Jasper AI content platform. Augment Jasper with niimo data and document skills." },
  { slug: "n8n",                name: "N8N",                   desc: "N8N workflow automation. Import niimo skills as N8N nodes for server-safe execution." },
  { slug: "make",               name: "Make",                  desc: "Make (Integromat) automation. Connect niimo skill nodes to Make visual workflows." },
  { slug: "zapier",             name: "Zapier",                desc: "Zapier automation. Trigger niimo skills from any Zapier workflow." },
  { slug: "nanobot",            name: "Nanobot",               desc: "Nanobot pip-install agent for 8+ messaging platforms including Telegram and Slack." },
  { slug: "zeroclaw",           name: "ZeroClaw",              desc: "ZeroClaw agent platform. Access niimo's certified skill library from ZeroClaw." },
  { slug: "composio",           name: "Composio",              desc: "Composio tool integration layer. Use niimo skills as Composio tool definitions." },
  { slug: "groq",               name: "Groq",                  desc: "Groq ultra-fast LLM inference. Execute niimo's 15,253 certified skills via Groq's OpenAI-compatible API." },
  { slug: "venice",             name: "Venice.ai",             desc: "Venice.ai privacy-first AI platform. Access niimo's certified skill library with native Skills support." },
  { slug: "lmstudio",           name: "LM Studio",             desc: "LM Studio local LLM runner. Point your LM Studio server at niimo skills for secure server-side execution." },
  { slug: "sambanova",          name: "SambaNova",             desc: "SambaNova enterprise AI inference. Integrate niimo's 15,253 certified skills into SambaNova agent pipelines." },
  { slug: "lobehub",            name: "LobeHub",               desc: "LobeHub open-source AI chat UI. Access the full niimo skill library via LobeHub's plugin ecosystem." },
  { slug: "elevenlabs",         name: "ElevenLabs",            desc: "ElevenLabs conversational AI. Run niimo certified skills natively inside ElevenLabs AI agents." },
  { slug: "komos",              name: "Komos.ai",              desc: "Komos.ai agent platform. Execute niimo's 15,253 server-side certified skills from Komos agent workflows." },
  { slug: "rork",               name: "Rork",                  desc: "Rork mobile app builder. Supercharge your Rork apps with niimo's certified AI skill library." },
  { slug: "flowtrail",          name: "Flowtrail",             desc: "Flowtrail AI workflow automation. Connect niimo skill nodes to Flowtrail agent pipelines." },
  { slug: "moltbook",           name: "Moltbook",              desc: "Moltbook AI workspace. Access niimo's certified skill library from Moltbook automations." },
  { slug: "base44",             name: "Base44",                desc: "Base44 no-code AI app builder. Embed niimo's 15,253 certified skills in your Base44 applications." },
  { slug: "mocha",              name: "GetMocha",              desc: "GetMocha AI agent platform. Execute certified niimo skills inside Mocha agent sessions." },
  { slug: "rocket-new",         name: "Rocket.new",            desc: "Rocket.new no-code AI builder. Integrate niimo skills via native Anthropic skill connectors." },
  { slug: "verdent",            name: "Verdent AI",            desc: "Verdent AI agent platform. Run niimo certified skills with Claude Skills compatibility." },
  { slug: "llmbase",            name: "LLMBase",               desc: "LLMBase AI skills registry. Discover and execute niimo's 15,253 certified skills via LLMBase." },
  { slug: "findskill",          name: "Findskill.ai",          desc: "Findskill.ai skill discovery platform. Find and activate niimo certified skills via single API key." },
  { slug: "termo",              name: "Termo.ai",              desc: "Termo.ai AI assistant platform. Access niimo's full certified skill library from Termo agent workflows." },
  { slug: "microsoft-skills",   name: "Microsoft AI Skills",   desc: "Microsoft AI Skills for Azure. Publish niimo certified skills as Azure Skills plugin endpoints." },
];

export const INTEGRATION_PAGES: { slug: string; name: string; desc: string }[] = [
  { slug: "slack",               name: "Slack",               desc: "Send messages, create channels, and automate team workflows with niimo Slack skills." },
  { slug: "gmail",               name: "Gmail",               desc: "Read, compose, and manage email at scale with niimo's certified Gmail skills." },
  { slug: "microsoftteams",      name: "Microsoft Teams",     desc: "Collaborate, schedule meetings, and automate Teams notifications via niimo." },
  { slug: "salesforce",          name: "Salesforce",          desc: "Query leads, update opportunities, and automate CRM workflows with niimo Salesforce skills." },
  { slug: "hubspot",             name: "HubSpot",             desc: "Manage contacts, pipelines, and marketing automation with niimo HubSpot skills." },
  { slug: "pipedrive",           name: "Pipedrive",           desc: "Track deals and automate your sales pipeline with niimo Pipedrive skills." },
  { slug: "xero",                name: "Xero",                desc: "Automate invoices, reconciliation, and financial reporting with niimo Xero skills." },
  { slug: "quickbooks",          name: "QuickBooks",          desc: "Sync transactions and manage bookkeeping with niimo QuickBooks skills." },
  { slug: "stripe",              name: "Stripe",              desc: "Handle payments, subscriptions, and revenue analytics with niimo Stripe skills." },
  { slug: "notion",              name: "Notion",              desc: "Read, create, and update Notion pages and databases with niimo skills." },
  { slug: "github",              name: "GitHub",              desc: "Manage repos, PRs, and issues with niimo GitHub automation skills." },
  { slug: "zapier",              name: "Zapier",              desc: "Trigger and chain multi-app automations using niimo Zapier skills." },
  { slug: "googlesheets",        name: "Google Sheets",       desc: "Read, write, and analyse spreadsheet data with niimo Google Sheets skills." },
  { slug: "shopify",             name: "Shopify",             desc: "Manage products, orders, and customer data with niimo Shopify skills." },
  { slug: "airtable",            name: "Airtable",            desc: "Query bases, create records, and build structured automations with niimo Airtable skills." },
  { slug: "openai",              name: "OpenAI",              desc: "Extend GPT-4 capabilities through chained niimo AI skill pipelines." },
  { slug: "jira",                name: "Jira",                desc: "Create, update, and triage Jira issues and sprints with niimo skills." },
  { slug: "asana",               name: "Asana",               desc: "Manage tasks, projects, and team workflows with niimo Asana skills." },
  { slug: "linear",              name: "Linear",              desc: "Track engineering issues and product roadmaps with niimo Linear skills." },
  { slug: "mondaydotcom",        name: "Monday.com",          desc: "Build no-code workflows across Monday boards with niimo automation skills." },
  { slug: "trello",              name: "Trello",              desc: "Manage Trello boards and cards with niimo skills." },
  { slug: "clickup",             name: "ClickUp",             desc: "Automate ClickUp tasks and workspace management with niimo skills." },
  { slug: "freshdesk",           name: "Freshdesk",           desc: "Resolve tickets, manage agents, and automate support with niimo Freshdesk skills." },
  { slug: "zendesk",             name: "Zendesk",             desc: "Automate ticket routing, macros, and reporting with niimo Zendesk skills." },
  { slug: "intercom",            name: "Intercom",            desc: "Manage customer conversations and automations with niimo Intercom skills." },
  { slug: "twilio",              name: "Twilio",              desc: "Send SMS, voice, and messaging at scale with niimo Twilio skills." },
  { slug: "sendgrid",            name: "SendGrid",            desc: "Automate transactional email and marketing campaigns with niimo SendGrid skills." },
  { slug: "mailchimp",           name: "Mailchimp",           desc: "Manage campaigns, audiences, and automations with niimo Mailchimp skills." },
  { slug: "dropbox",             name: "Dropbox",             desc: "Read, write, and organise files in Dropbox with niimo skills." },
  { slug: "onedrive",            name: "OneDrive",            desc: "Manage OneDrive files and folders with niimo automation skills." },
  { slug: "googledrive",         name: "Google Drive",        desc: "Upload, read, and organise Google Drive files with niimo skills." },
  { slug: "aws",                 name: "AWS",                 desc: "Automate S3, Lambda, and cloud resource management with niimo AWS skills." },
  { slug: "googlecloud",         name: "Google Cloud",        desc: "Manage GCP resources and services with niimo Google Cloud skills." },
  { slug: "azure",               name: "Microsoft Azure",     desc: "Automate Azure resource management and deployments with niimo skills." },
  { slug: "tableau",             name: "Tableau",             desc: "Fetch and refresh Tableau dashboards and data sources with niimo skills." },
  { slug: "powerbi",             name: "Power BI",            desc: "Automate Power BI reports and dataset refreshes with niimo skills." },
  { slug: "bigquery",            name: "BigQuery",            desc: "Run queries and manage BigQuery datasets with niimo skills." },
  { slug: "snowflake",           name: "Snowflake",           desc: "Query and manage Snowflake data warehouses with niimo skills." },
  { slug: "hubspotads",          name: "HubSpot Ads",         desc: "Manage ad campaigns and attribution with niimo HubSpot Ads skills." },
  { slug: "googleads",           name: "Google Ads",          desc: "Automate Google Ads campaigns, budgets, and reporting with niimo skills." },
  { slug: "facebookads",         name: "Facebook Ads",        desc: "Manage Meta ad campaigns and audiences with niimo skills." },
  { slug: "klaviyo",             name: "Klaviyo",             desc: "Personalise email and SMS marketing with niimo Klaviyo skills." },
  { slug: "bamboohr",            name: "BambooHR",            desc: "Manage employee records, PTO, and onboarding with niimo BambooHR skills." },
  { slug: "greenhouse",          name: "Greenhouse",          desc: "Automate recruitment pipelines with niimo Greenhouse skills." },
  { slug: "workday",             name: "Workday",             desc: "Access HR, payroll, and financial management data with niimo Workday skills." },
  { slug: "gusto",               name: "Gusto",               desc: "Automate payroll, benefits, and compliance with niimo Gusto skills." },
  { slug: "docusign",            name: "DocuSign",            desc: "Send, sign, and track contracts electronically with niimo DocuSign skills." },
  { slug: "googlecalendar",      name: "Google Calendar",     desc: "Schedule events and manage calendars with niimo Google Calendar skills." },
  { slug: "wordpress",           name: "WordPress",           desc: "Create and manage WordPress posts and pages with niimo skills." },
  { slug: "webflow",             name: "Webflow",             desc: "Manage CMS content and design workflows with niimo Webflow skills." },
  { slug: "ghost",               name: "Ghost",               desc: "Publish and manage newsletter and blog content with niimo Ghost skills." },
  { slug: "youtube",             name: "YouTube",             desc: "Fetch video data and channel analytics with niimo YouTube skills." },
  { slug: "instagram",           name: "Instagram",           desc: "Schedule posts and retrieve engagement metrics with niimo Instagram skills." },
  { slug: "tiktok",              name: "TikTok",              desc: "Analyse trends and manage TikTok content with niimo skills." },
  { slug: "x",                   name: "X / Twitter",         desc: "Post, monitor, and analyse social media presence with niimo X skills." },
  { slug: "facebook",            name: "Facebook",            desc: "Manage pages, ads, and audience engagement with niimo Facebook skills." },
  { slug: "nanoclaw",            name: "NanoClaw",            desc: "Container-isolated Claude Code agent runner with native niimo skill integration." },
  { slug: "openclaw",            name: "OpenClaw",            desc: "Open-source AI agent platform with niimo skills available natively on ClaWHub." },
  { slug: "huggingface",         name: "Hugging Face",        desc: "Deploy open-source models alongside niimo certified skills." },
  { slug: "pinecone",            name: "Pinecone",            desc: "Store and query vector embeddings at scale with niimo Pinecone skills." },
  { slug: "plaid",               name: "Plaid",               desc: "Retrieve bank transactions and financial data with niimo Plaid skills." },
  { slug: "make",                name: "Make",                desc: "Build visual automation workflows with niimo Make skills." },
];
