import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Post-build script: Generate robots.txt
 *
 * Emits a conventional crawler policy plus explicit rules for known AI
 * crawlers. The AI section defaults to allowing engines that cite and link
 * back (ChatGPT search, Perplexity, Claude search) while declining
 * training-only crawlers, which return no traffic.
 *
 * Set REACTEO_ALLOW_AI_TRAINING=true to allow training crawlers as well.
 */

// Crawlers that surface cited, linked answers — allowing these keeps the site
// eligible to appear in AI-generated results.
const AI_SEARCH_AGENTS = [
  'OAI-SearchBot',
  'Claude-SearchBot',
  'PerplexityBot',
  'DuckAssistBot',
  'YouBot',
];

// Crawlers that fetch a single URL because a user explicitly asked about it.
const AI_USER_AGENTS = ['ChatGPT-User', 'Claude-User', 'Perplexity-User', 'MistralAI-User'];

// Crawlers that collect model training corpora.
const AI_TRAINING_AGENTS = [
  'GPTBot',
  'ClaudeBot',
  'Google-Extended',
  'Applebot-Extended',
  'meta-externalagent',
  'Bytespider',
  'CCBot',
  'cohere-ai',
  'Diffbot',
  'Timpibot',
];

const PRIVATE_PATHS = ['/admin/', '/private/', '/.env', '/node_modules/'];

function block(userAgent, directives) {
  return `${[`User-agent: ${userAgent}`, ...directives].join('\n')}\n`;
}

const allowBlock = (ua) => block(ua, ['Allow: /', ...PRIVATE_PATHS.map((p) => `Disallow: ${p}`)]);
const denyBlock = (ua) => block(ua, ['Disallow: /']);

async function generateRobots() {
  try {
    const projectRoot = path.resolve(__dirname, '..');
    const distDir = path.resolve(projectRoot, 'dist');
    const robotsPath = path.join(distDir, 'robots.txt');

    const hostname = (process.env.VITE_SEO_HOSTNAME || 'https://localhost:5173').replace(/\/$/, '');
    const allowTraining = process.env.REACTEO_ALLOW_AI_TRAINING === 'true';

    const sections = [
      '# robots.txt generated by Reacteo',
      '',
      allowBlock('*'),
      '# AI answer engines — allowed so this site can be cited in AI results',
      ...AI_SEARCH_AGENTS.map(allowBlock),
      '# User-initiated fetches — a person explicitly asked about the URL',
      ...AI_USER_AGENTS.map(allowBlock),
      allowTraining
        ? '# AI training crawlers — allowed via REACTEO_ALLOW_AI_TRAINING'
        : '# AI training crawlers — disallowed (no traffic returned)',
      ...AI_TRAINING_AGENTS.map(allowTraining ? allowBlock : denyBlock),
      `Sitemap: ${hostname}/sitemap.xml`,
      `# llms.txt: ${hostname}/llms.txt`,
      '',
    ];

    if (!fs.existsSync(distDir)) {
      fs.mkdirSync(distDir, { recursive: true });
    }

    fs.writeFileSync(robotsPath, sections.join('\n'), 'utf-8');
    console.log(`✅ robots.txt generated successfully!`);
    console.log(`   Location: ${robotsPath}`);
    console.log(`   AI training crawlers: ${allowTraining ? 'allowed' : 'disallowed'}`);
  } catch (error) {
    console.error('❌ Error generating robots.txt:', error);
    process.exit(1);
  }
}

generateRobots();
